### ISSUE TITLE
add(int e) 를 만들어주세요.

### ISSUE THREAD

**Issue by jzqioipst** [jzqioipst/OurArrayList#2]
e값을 마지막 인덱스 뒤로 추가해줍니다.

만약 할당된 메모리가 부족하여 추가할 수 없다면 메모리크기를 현재 크기의 2배로 늘려주시고 값을 추가해주시면 됩니다.
이 때, 기존의 값들은 새로 할당된 메모리로 모두 옮겨져야 합니다.

**Comment by ansgml9884** [comment]
현재 크기의 2배로 늘리는 것 대신에 증가시킬 사이즈를 정해놓는 것이 더 낫지 않을까요?

**Comment by jzqioipst** [comment]
> 현재 크기의 2배로 늘리는 것 대신에 증가시킬 사이즈를 정해놓는 것이 더 낫지 않을까요?

메모리 크기를 확장하거나 축소할 때, 모든 요소들을 새로운 메모리로 복사해야하는 것은 큰 부담입니다. 더불어 새로운 메모리 공간을 할당 받는 것 자체도 좀 부담이긴 합니다.
그렇기에 되도록 메모리의 확장과 축소는 최대한 적게 일어나도록 유도하는 것이 맞고, 다루는 데이터의 양이 많다면 그 만큼 새로 넣거나 빼는 데이터의 양도 많을 가능성이 크기에 메모리의 크기는 상대적 비율로 늘리거나 줄이는 것이 맞습니다. 특히 데이터의 양이 많을 수록 새로운 메모리를 할당받아 옮기는 과정에 대한 부담이 크기 때문에 더더욱 그런 상황에서는 메모리의 확장과 축소가 가능한 적게 일어나야 합니다.
C++의 vector
Java의 ArrayList
Python의 list
위 3가지 언어의 동적배열들 모두 위와 같은 이유로 메모리의 사이즈를 고정된 값이 아닌 비율로써 늘리거나 줄입니다.

**Comment by ansgml9884** [comment]
아 그렇군요. 지금 상태로 유지하겠습니다. 답변 감사합니다!
